In [28]:
# program 1: Calculate total weekly from a list
daily_kwh = [500,400,700,600,300,200,500,600,400]
total_energy = sum(daily_kwh)
print("Total Energy Used:", total_energy, "kwh")

Total Energy Used: 4200 kwh

In [29]:
Building_usage = {
    "AIML": 300,
    "BOYS HOSTEL": 200
}
print("BOYS HOSTEL used:", Building_usage["BOYS HOSTEL"], "KWH")

BOYS HOSTEL used: 200 KWH

In [32]:
# Program 3: A Function to calculate electricity cost
def calculate_bill(kwh,rate_per_unit):
    return kwh * rate_per_unit

today_bill = calculate_bill(600,8)
print("Today's estimated bill is Rs.", today_bill)

Today's estimated bill is Rs. 4800

In [41]:
# program 4: Read a file line by line
with open("Campus_Energy.csv", "r") as file:
   for line in file.readlines():
      print(line.strip())

﻿Date,Building,KWH_Used,Peak_Hour_usage
5/10/2026,CSE,500,120
16-10-2026,HOSTAL,700,250
17-10-2026,CSE,400,110
18-10-2026,ECE,600,325
19-10-2026,CIVIL,300,210
20-10-2026,MECH,200,111
21-10-2026,AIML,500,320
22-10-2026,AIDS,600,250
23-10-2026,BBA,400,119

In [49]:
#import the pandas library
import pandas as pd

#Load the dataset you created
df = pd.read_csv("Campus_Energy.csv")

# Display the first row of the data
print("Here is the raw data:")
display(df.head())

# Group thr data to see total ususge per building
building_totals = df.groupby("Building")["KWH_used"].sum()
print("\nTotal ususge per building:")
print(building_totals)

# Generate a statistical summary(average,min,max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  KWH_Used  Peak_Hour_usage
0   5/10/2026      CSE       500              120
1  16-10-2026   HOSTAL       700              250
2  17-10-2026      CSE       400              110
3  18-10-2026      ECE       600              325
4  19-10-2026    CIVIL       300              210

Total usage per building:
Building
AIDS      600
AIML      500
BBA       400
CIVIL     300
CSE       900
ECE       600
HOSTAL    700
MECH      200
Name: KWH_Used, dtype: int64

Statistical Summary:

         KWH_Used  Peak_Hour_usage
count    9.000000         9.000000
mean   466.666667       201.666667
std    158.113883        89.500000
min    200.000000       110.000000
25%    400.000000       119.000000
50%    500.000000       210.000000
75%    600.000000       250.000000
max    700.000000       325.000000

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [51]:
# create the README.md file and write a message inside it

with open("README.md", "w") as file:
  file.write("# Smart Campus Energy project\n")
  file.write("This repository contains My week 1 hands-on Python and pandas assignments:\n")
  file.write("created by: [Karthik]")

  print("README.md has been successfully created")

README.md has been successfully created

In [ ]:
from google.colab import drive
drive.mount('/content/drive')